name: Ejecucion del Test Con Selenium

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Configura Gradle y habilita cache de dependencias
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    # Da permisos de ejecuci√≥n al wrapper
    - name: Grant execute permission for Gradlew
      run: chmod +x gradlew

    # Instala Chrome en el runner
    - name: Install Chrome
      run: sudo apt-get update && sudo apt-get install -y google-chrome-stable

    # Instala ChromeDriver en el runner
    - name: Install ChromeDriver
      run: sudo apt-get install -y chromium-chromedriver

    # Compila el proyecto
    - name: Build with Gradle Wrapper
      run: ./gradlew clean build

    # Ejecuta los tests
    - name: Run tests
      run: ./gradlew test "-Dcucumber.options=--tags @Courses"

    # Publica los reportes de pruebas como artefactos
    - name: Upload test reports
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: build/reports/tests/test
